# Generated by Django 3.2.5 on 2021-08-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('reportType', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('reportId', models.CharField(max_length=100)),
                ('referenceResourceId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('referenceResourceType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('referenceId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('referenceType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payload')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reference')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='ExpenseCategories',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Families',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeCategories',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
