# Generated by Django 3.2.5 on 2021-08-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_payload_reportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='ticketState',
            field=models.CharField(default='OPEN', max_length=16),
        ),
    ]
