# Generated by Django 3.2.5 on 2021-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reference_ticketstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='ticketState',
        ),
        migrations.AddField(
            model_name='reference',
            name='status',
            field=models.CharField(default='OPEN', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='ticketState',
            field=models.CharField(default='OPEN', max_length=16),
        ),
    ]
