# Generated by Django 3.2.5 on 2021-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_payload_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='message',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
